'use client'

import { useState } from 'react'
import { Solution } from '@/types'

interface SolutionViewProps {
  solution: Solution
  onRegenerate?: () => void
  isRegenerating?: boolean
}

// Clean markdown formatting from text
const cleanMarkdown = (text: string): string => {
  if (!text) return text
  return text
    .replace(/\*\*\*(.+?)\*\*\*/g, '$1')  // Remove triple asterisks
    .replace(/\*\*(.+?)\*\*/g, '$1')      // Remove bold markdown
    .replace(/\*(.+?)\*/g, '$1')          // Remove italic markdown
    .replace(/_{3}(.+?)_{3}/g, '$1')      // Remove triple underscores
    .replace(/__(.+?)__/g, '$1')          // Remove double underscores
    .replace(/_(.+?)_/g, '$1')            // Remove single underscores
}

export default function SolutionView({ solution, onRegenerate, isRegenerating = false }: SolutionViewProps) {
  const [activeTab, setActiveTab] = useState<'overview' | 'steps' | 'reasoning'>('overview')
  const [feedbackRating, setFeedbackRating] = useState(solution.feedback_rating || 0)

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const handleFeedbackRating = (rating: number) => {
    setFeedbackRating(rating)
    // TODO: Send rating to API
    console.log('Rating submitted:', rating)
  }

  const tabs = [
    { id: 'overview', label: 'Overview', icon: '📋' },
    { id: 'steps', label: 'Step-by-Step', icon: '📝' },
    { id: 'reasoning', label: 'Reasoning', icon: '🧠' },
  ]

  return (
    <div className="bg-white rounded-lg shadow border border-gray-200 overflow-hidden mt-6">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-200 bg-green-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center">
                <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
            <div className="ml-3">
              <h2 className="text-lg font-semibold text-green-900">AI-Generated Solution</h2>
              <p className="text-sm text-green-700">
                Generated by {solution.ai_model_used || solution.model_used} • Confidence: {Math.round((solution.confidence_score || 0) * 100)}%
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            {onRegenerate && (
              <button
                onClick={onRegenerate}
                disabled={isRegenerating}
                className="px-3 py-1.5 bg-white hover:bg-gray-50 disabled:bg-gray-100 text-green-700 border border-green-300 rounded-md text-sm font-medium flex items-center gap-2 transition-colors"
                title="Generate a new solution"
              >
                {isRegenerating ? (
                  <>
                    <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Regenerating...
                  </>
                ) : (
                  <>
                    <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    Regenerate
                  </>
                )}
              </button>
            )}
            <div className="text-right">
              <div className="text-sm text-green-600">
                {formatDate(solution.created_at || solution.generated_at)}
              </div>
              <div className="text-xs text-green-500">
                Processing time: {solution.processing_time || 0}s
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="border-b border-gray-200">
        <nav className="-mb-px flex space-x-8 px-6" aria-label="Tabs">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap ${
                activeTab === tab.id
                  ? 'border-primary-500 text-primary-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              <span className="mr-2">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Tab Content */}
      <div className="px-6 py-6">
        {activeTab === 'overview' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-3">Solution Overview</h3>
              <div className="prose prose-sm max-w-none text-gray-700">
                <p className="whitespace-pre-wrap">{cleanMarkdown(solution.content)}</p>
              </div>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-3">Explanation</h3>
              <div className="prose prose-sm max-w-none text-gray-700">
                <p className="whitespace-pre-wrap">{cleanMarkdown(solution.explanation || 'No detailed explanation available.')}</p>
              </div>
            </div>

            {/* Solution Metadata */}
            <div className="bg-gray-50 rounded-lg p-4">
              <h4 className="text-sm font-medium text-gray-900 mb-2">Solution Details</h4>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                <div>
                  <span className="text-gray-500">Model:</span>
                  <span className="text-gray-900 ml-1 font-medium">{solution.ai_model_used || solution.model_used}</span>
                </div>
                <div>
                  <span className="text-gray-500">Confidence:</span>
                  <span className="text-gray-900 ml-1 font-medium">{Math.round((solution.confidence_score || 0) * 100)}%</span>
                </div>
                <div>
                  <span className="text-gray-500">Subject:</span>
                  <span className="text-gray-900 ml-1 font-medium">{solution.subject_area || 'N/A'}</span>
                </div>
                <div>
                  <span className="text-gray-500">Validated:</span>
                  <span className={`ml-1 font-medium ${solution.quality_validated ? 'text-green-600' : 'text-yellow-600'}`}>
                    {solution.quality_validated ? 'Yes' : 'Pending'}
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'steps' && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Step-by-Step Solution</h3>
            <div className="space-y-3">
              {solution.step_by_step && solution.step_by_step.map((stepObj, index) => {
                const stepText = typeof stepObj === 'string' ? stepObj : stepObj.step
                const explanation = typeof stepObj === 'object' && stepObj.explanation ? stepObj.explanation : ''
                
                if (stepText.trim() === '') {
                  return <div key={index} className="h-4" />
                }
                
                const isHeader = stepText.startsWith('Problem') || stepText.includes(':') && !stepText.startsWith('Step')
                
                return (
                  <div
                    key={index}
                    className={`${
                      isHeader
                        ? 'bg-blue-50 border-l-4 border-blue-400 p-3 rounded-r-lg'
                        : 'bg-gray-50 p-3 rounded-lg ml-4'
                    }`}
                  >
                    <div className={`${isHeader ? 'font-semibold text-blue-900' : 'text-gray-800'}`}>
                      {cleanMarkdown(stepText)}
                    </div>
                    {explanation && (
                      <div className="mt-2 text-sm text-gray-600 ml-4">
                        {cleanMarkdown(explanation)}
                      </div>
                    )}
                  </div>
                )
              })}
              {solution.steps && !solution.step_by_step && solution.steps.map((step, index) => {
                if (step.trim() === '') {
                  return <div key={index} className="h-4" />
                }
                
                const isHeader = step.startsWith('Problem') || step.includes(':') && !step.startsWith('Step')
                
                return (
                  <div
                    key={index}
                    className={`${
                      isHeader
                        ? 'bg-blue-50 border-l-4 border-blue-400 p-3 rounded-r-lg'
                        : 'bg-gray-50 p-3 rounded-lg ml-4'
                    }`}
                  >
                    <div className={`${isHeader ? 'font-semibold text-blue-900' : 'text-gray-800'}`}>
                      {cleanMarkdown(step)}
                    </div>
                  </div>
                )
              })}
              {!solution.step_by_step && !solution.steps && (
                <p className="text-gray-500">No step-by-step solution available.</p>
              )}
            </div>
          </div>
        )}

        {activeTab === 'reasoning' && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Reasoning & Methodology</h3>
            <div className="prose prose-sm max-w-none text-gray-700">
              <p className="whitespace-pre-wrap">{cleanMarkdown(solution.reasoning || 'No reasoning details available.')}</p>
            </div>
            
            <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  <svg className="h-5 w-5 text-blue-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                  </svg>
                </div>
                <div className="ml-3">
                  <h4 className="text-sm font-medium text-blue-800">AI Methodology Note</h4>
                  <p className="mt-1 text-sm text-blue-700">
                    This solution was generated using advanced AI reasoning capabilities. The approach focuses on 
                    educational value, showing multiple methods where applicable and explaining the rationale 
                    behind each step to enhance learning.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Feedback Section */}
      <div className="border-t border-gray-200 px-6 py-4 bg-gray-50">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-sm font-medium text-gray-900">Rate this solution</h4>
            <p className="text-xs text-gray-500">Help us improve our AI-generated solutions</p>
          </div>
          <div className="flex items-center space-x-1">
            {[1, 2, 3, 4, 5].map((rating) => (
              <button
                key={rating}
                onClick={() => handleFeedbackRating(rating)}
                className={`p-1 rounded-full hover:bg-gray-200 transition-colors ${
                  rating <= feedbackRating ? 'text-yellow-400' : 'text-gray-300'
                }`}
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                </svg>
              </button>
            ))}
            {feedbackRating > 0 && (
              <span className="ml-2 text-sm text-gray-600">
                {feedbackRating}/5
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}